env:
  TERM: xterm-256color
window:
  padding:
    x: 3
    y: 3
  dynamic_padding: false
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
scrolling:
  history: 5000
  multiplier: 3
  auto_scroll: false
font:
  normal:
    family: Source Code Pro
    style: Medium
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  bold_italic:
    family: Source Code Pro
    style: Bold Italic
  size: 7.5
  offset:
    x: 0
    y: 1
draw_bold_text_with_bright_colors: true
colors:
  name: 3024 (dark)
  author: Chris Kempson
  primary:
    background: "#090300"
    foreground: "#a5a2a2"
  cursor:
    text: "#090300"
    cursor: "#a5a2a2"
  normal:
    black: "#090300"
    red: "#db2d20"
    green: "#01a252"
    yellow: "#fded02"
    blue: "#01a0e4"
    magenta: "#a16a94"
    cyan: "#b5e4f4"
    white: "#a5a2a2"
  bright:
    black: "#5c5855"
    red: "#db2d20"
    green: "#01a252"
    yellow: "#fded02"
    blue: "#01a0e4"
    magenta: "#a16a94"
    cyan: "#b5e4f4"
    white: "#f7f7f7"
background_opacity: 1
shell:
  program: /bin/bash
key_bindings:
  - key: V
    mods: Control|Shift
    action: Paste
  - key: P
    mods: Alt
    action: Paste
  - key: C
    mods: Control|Shift
    action: Copy
  - key: Y
    mods: Alt
    action: Copy
  - key: Insert
    mods: Shift
    action: PasteSelection
  - key: Key0
    mods: Control
    action: ResetFontSize
  - key: Equals
    mods: Control
    action: IncreaseFontSize
  - key: Plus
    mods: Control
    action: IncreaseFontSize
  - key: Minus
    mods: Control
    action: DecreaseFontSize
  - key: Minus
    mods: Control
    action: DecreaseFontSize
  - key: Paste
    mods: None
    action: Paste
  - key: Copy
    mods: None
    action: Copy
  - key: L
    mods: Control
    action: ClearLogNotice
  - key: L
    mods: Control
    chars: "\f"
  - key: PageUp
    mods: None
    action: ScrollHalfPageUp
    mode: ~Alt
  - key: PageDown
    mods: None
    action: ScrollHalfPageDown
    mode: ~Alt
  - key: PageUp
    mods: Alt
    action: ScrollToTop
    mode: ~Alt
  - key: PageDown
    mods: Alt
    action: ScrollToBottom
    mode: ~Alt
