env:
  TERM: xterm-256color
window:
  padding:
    x: 3
    y: 3
  dynamic_padding: false
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
scrolling:
  history: 5000
  multiplier: 3
  auto_scroll: false
font:
  normal:
    family: Fira Code
    style: Medium
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  bold_italic:
    family: Fira Code
    style: Bold Italic
  size: 7.5
  offset:
    x: 0
    y: 1
draw_bold_text_with_bright_colors: true
colors:
  # Default colors
  primary:
    background: '#1f1f1f'
    foreground: '#e5e1d8'

  # Normal colors
  normal:
    black: '#000000'
    red: '#f7786d'
    green: '#bde97c'
    yellow: '#efdfac'
    blue: '#6ebaf8'
    magenta: '#ef88ff'
    cyan: '#90fdf8'
    white: '#e5e1d8'

  # Bright colors
  bright:
    black: '#b4b4b4'
    red: '#f99f92'
    green: '#e3f7a1'
    yellow: '#f2e9bf'
    blue: '#b3d2ff'
    magenta: '#e5bdff'
    cyan: '#c2fefa'
    white: '#ffffff'
background_opacity: 1
shell:
  program: /usr/bin/zsh
key_bindings:
  - key: V
    mods: Control|Shift
    action: Paste
  - key: P
    mods: Alt
    action: Paste
  - key: C
    mods: Control|Shift
    action: Copy
  - key: Y
    mods: Alt
    action: Copy
  - key: Insert
    mods: Shift
    action: PasteSelection
  - key: Key0
    mods: Control
    action: ResetFontSize
  - key: Equals
    mods: Control
    action: IncreaseFontSize
  - key: Plus
    mods: Control
    action: IncreaseFontSize
  - key: Minus
    mods: Control
    action: DecreaseFontSize
  - key: Minus
    mods: Control
    action: DecreaseFontSize
  - key: Paste
    mods: None
    action: Paste
  - key: Copy
    mods: None
    action: Copy
  - key: L
    mods: Control
    action: ClearLogNotice
  - key: L
    mods: Control
    chars: "\f"

  - key: Space
    mods: Control
    action: ToggleViMode
  - key: U
    mods: Control
    action: ScrollHalfPageUp
    mode: ~Alt
  - key: D
    mods: Control
    action: ScrollHalfPageDown
    mode: ~Alt
  - key: T
    mods: Alt
    chars: "theme\r"

  - key: PageUp
    mods: Alt
    action: ScrollToTop
    mode: ~Alt
  - key: PageDown
    mods: Alt
    action: ScrollToBottom
    mode: ~Alt
