#!/bin/bash

cp /home/zim/.urxvt.darker /home/zim/.Xresources
xrdb /home/zim/.Xresources
sed -i 's/set background=light/set background=dark/g' ~/.vimrc
sed -i 's/quietlight/monokai-phoenix/g' ~/.vimrc
sed -i 's/set background=light/set background=dark/g' /root/.vimrc
sed -i 's/quietlight/monokai-phoenix/g' /root/.vimrc

