
require('settings')
require('autocmds')
require('plugins/packer')
require('plugins/nvim-colorizer')
require('plugins/nvim-lspconfig')
require('plugins/telescope-fzf-native')
require('plugins/comfortable-motion')
require('plugins/nvim-treesitter')
require('plugins/nvim-autopairs')
require('plugins/headlines-nvim')
require('plugins/renamer-nvim')
require('plugins/nvim-neorg')
require('plugins/nvim-tree')
require('plugins/telescope')
require('plugins/venn-nvim')
require('plugins/hop-nvim')
require('plugins/nvim-cmp')
require('plugins/feline')
require('compiler')
require('mappings')

-- Needs to be loaded in the end 
require('plugins/tabout-nvim')
