
require('settings')
require('autocmds')
require('plugins/packer')
require('plugins/org-bullets')
require('plugins/nvim-colorizer')
require('plugins/telescope-fzf-native')
require('plugins/comfortable-motion')
require('plugins/nvim-treesitter')
require('plugins/nvim-autopairs')
require('plugins/headlines-nvim')
require('plugins/orgmode-nvim')
require('plugins/nvim-tree')
require('plugins/telescope')
require('plugins/hop-nvim')
require('plugins/feline')
require('compiler')
require('mappings')

-- Needs to be loaded in the end 
require('plugins/tabout-nvim')
