# ~/.bashrc

# global variables
export LANG=en_US.UTF-8
export TERM='xterm-256color' 
export DARKO='tokyonight'
export LIGHTO='gruvbox'

# URxvt content erased workaround
for (( i=1; i<=$LINES; i++ )); do echo; done; clear

# Bash Prompt
PS1="\[\e[1;33m\] [\u@\w]  >> "

# VI MODE
set -o vi

# vi settings                                         
$if mode=vi                
    # normal mode                           
    set keymap vi-command                                 
    "A": 0
    "Z": $
    "AA": 0i
    "ZZ": $a
$endif 

# Aliases
alias ls='ls --color=auto'
alias x="exit"
alias l="ls" 
alias ll="ls -la" 
alias c="clear" 
alias v='nvim'
alias sv='sudo nvim'
alias brc="nvim ~/.bashrc"
alias vrc="nvim ~/.config/nvim/init.vim"
alias zrc="nvim ~/.zshrc"
alias sbrc="source ~/.bashrc"
alias svrc="source ~/.config/nvim/init.vim"
alias szrc="source ~/.zshrc"
alias cf="cd /opt/dwm && nvim config.def.h"
alias td="nvim ~/.todo.txt" 
alias pacman="sudo pacman" 
alias torr='transmission-cli -w ~/torrents -D -u 30' 
alias dragon="dragon-drag-and-drop" 

alias suspend='systemctl suspend && slock'
alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'


source ~/.local/share/blesh/ble.sh
