#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# setxkbmap -option altwin:swap_lalt_lwin
# setxkbmap -option caps:swapescape

feh --bg-scale ~/pictures/minimal/archneon.png
/opt/bar/dwm_bar.sh &
nm-applet --indicator &
mate-power-manager &

while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    nm-applet --indicator &
    mate-power-manager &
    # No error logging
    #dwm >/dev/null 2>&1
done
 
exec i3
