# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export TERM='xterm-256color'
export LANG=en_US.UTF-8
export MYVIMRC="$HOME/.config/nvim/init.lua"
export darko='hydrangea'
export lighto='gruvbox'

source /home/zim/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/powerlevel10k/powerlevel10k.zsh-theme

# urxvt content gets erased workaround
for (( i=1; i<=$LINES; i++ )); do echo; done; clear

bindkey -v
bindkey '^E' autosuggest-accept
setopt autocd

bindkey '^H' backward-kill-word

HISTFILE=~/.zsh_history
HISTSIZE=3960
SAVEHIST=3960
setopt appendhistory

# Aliases
alias l="ls"
alias k="kak"
alias v="nvim"
alias x="exit"
alias c="clear"
alias ll="ls -la"
alias fm="ranger"
alias sv="sudo nvim"
alias zrc="nvim ~/.zshrc"
alias pacman="sudo pacman"
alias brc="nvim ~/.bashrc"
alias td="nvim ~/.todo.txt"
alias szrc="source ~/.zshrc"
alias sbrc="source ~/.bashrc"
alias history="cat ~/.zsh_history"
alias dragon="dragon-drag-and-drop"
alias vrc="nvim ~/.config/nvim/init.vim"
alias svrc="source ~/.config/nvim/init.vim"
alias cf="cd /opt/dwm && nvim config.def.h"
alias torr='transmission-cli -w ~/torrents -D -u 30'

alias suspend='systemctl suspend && slock'
alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
