#!/bin/bash

cp /home/zim/.github/dotfiles/config/urxvt/urxvt.dark /home/zim/.Xresources
xrdb /home/zim/.Xresources
sed -i 's/set background=light/set background=dark/g' /home/zim/.config/nvim/init.vim
sed -i "s/colorscheme $LIGHTO/colorscheme $DARKO/g" /home/zim/.config/nvim/init.vim
