#!/bin/bash
while true; do
    workspace=0
    echo -ne "GOTO? a1 s2 d3 f4 g5 h6 j7 k8 l9: \n\n    "
    read -r -n 1 tag
    sleep .3
    case $tag in
        a | 1) workspace=1 ;;
        s | 2) workspace=2 ;;
        d | 3) workspace=3 ;;
        f | 4) workspace=4 ;;
        g | 5) workspace=5 ;;
        h | 6) workspace=6 ;;
        j | 7) workspace=7 ;;
        k | 8) workspace=8 ;;
        * | 9) workspace=9 ;;
    esac
    xdotool key Super+$workspace
    clear
done
