#!/bin/bash

cp /home/zim/.github/dotfiles/config/urxvt/urxvt.light /home/zim/.Xresources
xrdb /home/zim/.Xresources
sed -i 's/set background=dark/set background=light/g' /home/zim/.vimrc
sed -i "s/colorscheme $DARKO/colorscheme $LIGHTO/g" /home/zim/.vimrc
